name: Frontend Build and Deploy to s3.

on:
  push:
    branches: [ "main" ]


jobs:
  build_and_deploy_job:
    name: Make dist package
    runs-on: self-hosted
    permissions:
      contents: read
      issues: write   
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      env:
        GH_TOKEN: ${{ secrets.GIT_TOKEN }}
      with:
        ref: main
      

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '20.12.0'
    - name: Install dependencies
      run: |
        npm install yarn --global
        yarn install
        yarn build

    - name: Increase package.json version
      run: |
          git config  user.name 'amish-git'
          git config  user.email 'amishthapa72@gmail.com'
          npm version patch --no-git-tag-version
          git add package.json
          git commit -m "Increase package.json version and push"
          
          git push https://$GH_TOKEN@github.com/amish-git/react_vite.git "main"
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Push dist's files to S3 bucket
      run: |
        aws s3 cp ./dist/ s3://amish-workflow-bucket --recursive

    - name: Invalidating CloudFront Cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
   
    
